/* GENERATED by scripts/capture.mjs. Do not edit.
 * Operations, fields and routing: /Users/admin/CompoundLabs/n8n-nodes-compound/nodes/ParseRail/description.ts
 * Prices, groups, units, throttles and the pause: /Users/admin/CompoundLabs/parserail/src/lib/platform/constants.ts
 * Captured 2026-10-02.
 */

export const CAPTURED_AT = "2026-10-02" as const;

export const NODE_VERSION = "0.3.5" as const;

export const NODE_NAME = "n8n-nodes-compound" as const;

export const NODE_DISPLAY = "ParseRail" as const;

export const NODE_INTERNAL = "parseRail" as const;

export const API_VERSION = 1 as const;

export const KEYWORDS = [
 "n8n-community-node-package",
 "compound-labs",
 "parserail",
 "ai",
 "document-parsing",
 "invoice-ocr",
 "extraction"
] as const;

export const LICENCE = "MIT" as const;

export const HOMEPAGE = "https://parserail.thecompound.tech" as const;

export const REPO = "https://github.com/kyisaiah47/n8n-nodes-compound" as const;

export const N8N_BLOCK = {
 "n8nNodesApiVersion": 1,
 "credentials": [
  "dist/credentials/ParseRailApi.credentials.js"
 ],
 "nodes": [
  "dist/nodes/ParseRail/ParseRail.node.js"
 ]
} as const;

export const USABLE_AS_TOOL = true as const;

export const REQUEST_BASE = "https://api.thecompound.tech" as const;

export const DECLARED_COUNT = 39 as const;

export const CREDIT_USD = 0.01 as const;

export const FIELD_COUNT = 16 as const;

export const CREDENTIAL = {
 "name": "parseRailApi",
 "displayName": "ParseRail API",
 "docs": "https://parserail.thecompound.tech/docs",
 "header": "Authorization: Bearer <apiKey>",
 "testBaseUrl": "https://api.thecompound.tech",
 "testUrl": "/v1/account"
} as const;

export const GROUPS = [
 {
  "key": "documents",
  "title": "Documents",
  "blurb": "Any document in. Clean, schema-valid JSON out."
 },
 {
  "key": "extract",
  "title": "Extract & structure",
  "blurb": "Messy input → data your code can trust."
 },
 {
  "key": "commerce",
  "title": "Commerce & ops",
  "blurb": "Disputes, collections, quotes, and fraud , handled."
 },
 {
  "key": "communication",
  "title": "Communication",
  "blurb": "Replies, triage, minutes, and outreach, ready to send."
 },
 {
  "key": "content",
  "title": "Content & moderation",
  "blurb": "On-brand copy in; policy-breaking content out."
 },
 {
  "key": "web",
  "title": "Web & research",
  "blurb": "Live, cited answers from the real web."
 },
 {
  "key": "media",
  "title": "Media & agents",
  "blurb": "Voice, images, transcripts , and memory that persists."
 }
] as const;

export const PACKS = [
 {
  "id": "starter",
  "usd": 20,
  "credits": 2000,
  "label": "Starter , $20"
 },
 {
  "id": "growth",
  "usd": 100,
  "credits": 10500,
  "label": "Growth , $100 (+5% bonus)"
 },
 {
  "id": "scale",
  "usd": 500,
  "credits": 55000,
  "label": "Scale , $500 (+10% bonus)"
 }
] as const;

export const OPERATIONS = [
 {
  "value": "parse",
  "name": "Document Parse",
  "action": "Document Parse",
  "line": "Any invoice, receipt, EOB, ERA, or COI , PDF or image , into structured, validated JSON.",
  "method": "POST",
  "path": "/v1/parse",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "parse",
  "group": "documents",
  "unit": "document",
  "blurb": "Any invoice, receipt, EOB, ERA, or COI , PDF or image , into structured, validated JSON.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "extract",
  "name": "Field Extraction",
  "action": "Field Extraction",
  "line": "Pull a field set you define out of any block of text. You name the fields; you get typed values with confidence.",
  "method": "POST",
  "path": "/v1/extract",
  "fields": [],
  "key": "extract",
  "group": "extract",
  "unit": "call",
  "blurb": "Pull a field set you define out of any block of text. You name the fields; you get typed values with confidence.",
  "credits": 4,
  "usd": 0.04,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "classify",
  "name": "Classification",
  "action": "Classification",
  "line": "Route or tag text against your own taxonomy , a label, a confidence, and a one-line rationale.",
  "method": "POST",
  "path": "/v1/classify",
  "fields": [],
  "key": "classify",
  "group": "extract",
  "unit": "call",
  "blurb": "Route or tag text against your own taxonomy , a label, a confidence, and a one-line rationale.",
  "credits": 2,
  "usd": 0.02,
  "rate": {
   "limit": 300,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "summarize",
  "name": "Summarize",
  "action": "Summarize",
  "line": "A meeting transcript, thread, or report → a tight summary, key points, and extracted action items.",
  "method": "POST",
  "path": "/v1/summarize",
  "fields": [],
  "key": "summarize",
  "group": "communication",
  "unit": "call",
  "blurb": "A meeting transcript, thread, or report → a tight summary, key points, and extracted action items.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "redact",
  "name": "PII Redaction",
  "action": "PII Redaction",
  "line": "Detect and strip names, emails, phones, SSNs, cards, and PHI from text before you store or log it.",
  "method": "POST",
  "path": "/v1/redact",
  "fields": [],
  "key": "redact",
  "group": "content",
  "unit": "call",
  "blurb": "Detect and strip names, emails, phones, SSNs, cards, and PHI from text before you store or log it.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "sentiment",
  "name": "Sentiment",
  "action": "Sentiment",
  "line": "Turn a review or support message into a sentiment score, per-aspect breakdown, and the themes driving it.",
  "method": "POST",
  "path": "/v1/sentiment",
  "fields": [],
  "key": "sentiment",
  "group": "communication",
  "unit": "call",
  "blurb": "Turn a review or support message into a sentiment score, per-aspect breakdown, and the themes driving it.",
  "credits": 2,
  "usd": 0.02,
  "rate": {
   "limit": 300,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "contract",
  "name": "Contract Analysis",
  "action": "Contract Analysis",
  "line": "A contract → parties, effective date, term, renewal, governing law, obligations, and flagged risk clauses.",
  "method": "POST",
  "path": "/v1/contract",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "contract",
  "group": "documents",
  "unit": "contract",
  "blurb": "A contract → parties, effective date, term, renewal, governing law, obligations, and flagged risk clauses.",
  "credits": 12,
  "usd": 0.12,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "chargeback",
  "name": "Chargeback Representment",
  "action": "Chargeback Representment",
  "line": "Dispute details → a representment narrative, an evidence checklist, the right reason code, and a win-likelihood.",
  "method": "POST",
  "path": "/v1/chargeback",
  "fields": [],
  "key": "chargeback",
  "group": "commerce",
  "unit": "dispute",
  "blurb": "Dispute details → a representment narrative, an evidence checklist, the right reason code, and a win-likelihood.",
  "credits": 15,
  "usd": 0.15,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "enrich",
  "name": "Company Enrichment",
  "action": "Company Enrichment",
  "line": "A domain or work email → a structured company profile: name, description, industry, HQ, size, and links.",
  "method": "POST",
  "path": "/v1/enrich",
  "fields": [],
  "key": "enrich",
  "group": "web",
  "unit": "lookup",
  "blurb": "A domain or work email → a structured company profile: name, description, industry, HQ, size, and links.",
  "credits": 5,
  "usd": 0.05,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "invoice",
  "name": "Invoice Extraction",
  "action": "Invoice Extraction",
  "line": "An invoice , PDF, photo, or text , into vendor, dates, PO refs, tax, totals, and clean line items.",
  "method": "POST",
  "path": "/v1/invoice",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "invoice",
  "group": "documents",
  "unit": "invoice",
  "blurb": "An invoice , PDF, photo, or text , into vendor, dates, PO refs, tax, totals, and clean line items.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "receipt",
  "name": "Receipt Extraction",
  "action": "Receipt Extraction",
  "line": "A receipt into merchant, items, totals, payment method, and an expense category , built for expense flows.",
  "method": "POST",
  "path": "/v1/receipt",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "receipt",
  "group": "documents",
  "unit": "receipt",
  "blurb": "A receipt into merchant, items, totals, payment method, and an expense category , built for expense flows.",
  "credits": 6,
  "usd": 0.06,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "statement",
  "name": "Statement Parsing",
  "action": "Statement Parsing",
  "line": "A bank or card statement into the account, the period, balances, and every transaction as a normalized row.",
  "method": "POST",
  "path": "/v1/statement",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "statement",
  "group": "documents",
  "unit": "statement",
  "blurb": "A bank or card statement into the account, the period, balances, and every transaction as a normalized row.",
  "credits": 12,
  "usd": 0.12,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "resume",
  "name": "Resume Parsing",
  "action": "Resume Parsing",
  "line": "A resume or CV into a structured candidate profile: contact, skills, experience, education, and links.",
  "method": "POST",
  "path": "/v1/resume",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "resume",
  "group": "documents",
  "unit": "resume",
  "blurb": "A resume or CV into a structured candidate profile: contact, skills, experience, education, and links.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "tables",
  "name": "Table Extraction",
  "action": "Table Extraction",
  "line": "Every table in a document , even scanned , as clean headers and rows, ready for your spreadsheet or DB.",
  "method": "POST",
  "path": "/v1/tables",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "tables",
  "group": "documents",
  "unit": "document",
  "blurb": "Every table in a document , even scanned , as clean headers and rows, ready for your spreadsheet or DB.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "split",
  "name": "Document Splitting",
  "action": "Document Splitting",
  "line": "A multi-document scan bundle classified and split: what each document is, where it starts and ends, and a summary.",
  "method": "POST",
  "path": "/v1/split",
  "fields": [
   {
    "label": "File URL",
    "name": "fileUrl",
    "type": "string",
    "required": false,
    "hint": "Public URL to a PDF or image. Provide this or Text."
   },
   {
    "label": "Text",
    "name": "text",
    "type": "string",
    "required": false,
    "hint": "Raw text, if you already have it. Provide this or File URL."
   }
  ],
  "key": "split",
  "group": "documents",
  "unit": "bundle",
  "blurb": "A multi-document scan bundle classified and split: what each document is, where it starts and ends, and a summary.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": true
 },
 {
  "value": "compare",
  "name": "Document Comparison",
  "action": "Document Comparison",
  "line": "Two versions of a contract or document → every material change, what it means, and the risk it carries.",
  "method": "POST",
  "path": "/v1/compare",
  "fields": [],
  "key": "compare",
  "group": "documents",
  "unit": "comparison",
  "blurb": "Two versions of a contract or document → every material change, what it means, and the risk it carries.",
  "credits": 15,
  "usd": 0.15,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "structure",
  "name": "Structure to Your Schema",
  "action": "Structure to Your Schema",
  "line": "Any messy input , text, HTML, an email , plus YOUR JSON schema → output shaped to it, validated against your required fields and property types, with an automatic corrective retry and a `valid` flag.",
  "method": "POST",
  "path": "/v1/structure",
  "fields": [],
  "key": "structure",
  "group": "extract",
  "unit": "call",
  "blurb": "Any messy input , text, HTML, an email , plus YOUR JSON schema → output shaped to it, validated against your required fields and property types, with an automatic corrective retry and a `valid` flag.",
  "credits": 6,
  "usd": 0.06,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "normalize",
  "name": "Record Normalization",
  "action": "Record Normalization",
  "line": "A batch of messy records → clean canonical rows, with a change log of every fix (casing, formats, dedup-ready values).",
  "method": "POST",
  "path": "/v1/normalize",
  "fields": [],
  "key": "normalize",
  "group": "extract",
  "unit": "batch",
  "blurb": "A batch of messy records → clean canonical rows, with a change log of every fix (casing, formats, dedup-ready values).",
  "credits": 5,
  "usd": 0.05,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "match",
  "name": "Entity Matching",
  "action": "Entity Matching",
  "line": "Two record sets → which rows are the same real-world thing, with confidence and reasoning. Fuzzy names, typos, aliases handled.",
  "method": "POST",
  "path": "/v1/match",
  "fields": [],
  "key": "match",
  "group": "extract",
  "unit": "run",
  "blurb": "Two record sets → which rows are the same real-world thing, with confidence and reasoning. Fuzzy names, typos, aliases handled.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "categorize",
  "name": "Batch Categorization",
  "action": "Batch Categorization",
  "line": "Up to a hundred items against your taxonomy in one call , products, transactions, tickets , each with a confidence.",
  "method": "POST",
  "path": "/v1/categorize",
  "fields": [],
  "key": "categorize",
  "group": "extract",
  "unit": "batch",
  "blurb": "Up to a hundred items against your taxonomy in one call , products, transactions, tickets , each with a confidence.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "dunning",
  "name": "Collections Sequence",
  "action": "Collections Sequence",
  "line": "An overdue invoice → a ready-to-send collection sequence, escalating at the right pace and tone for how late it is.",
  "method": "POST",
  "path": "/v1/dunning",
  "fields": [],
  "key": "dunning",
  "group": "commerce",
  "unit": "sequence",
  "blurb": "An overdue invoice → a ready-to-send collection sequence, escalating at the right pace and tone for how late it is.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "po-match",
  "name": "3-Way Match",
  "action": "3-Way Match",
  "line": "Invoice vs purchase order vs receipt → matched, partial, or mismatched, with every discrepancy flagged and sized.",
  "method": "POST",
  "path": "/v1/po-match",
  "fields": [],
  "key": "po-match",
  "group": "commerce",
  "unit": "match",
  "blurb": "Invoice vs purchase order vs receipt → matched, partial, or mismatched, with every discrepancy flagged and sized.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "quote",
  "name": "Quote Builder",
  "action": "Quote Builder",
  "line": "A job description plus your rates → an itemized, professional quote with assumptions and scope notes spelled out.",
  "method": "POST",
  "path": "/v1/quote",
  "fields": [],
  "key": "quote",
  "group": "commerce",
  "unit": "quote",
  "blurb": "A job description plus your rates → an itemized, professional quote with assumptions and scope notes spelled out.",
  "credits": 8,
  "usd": 0.08,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "fraud-flag",
  "name": "Fraud Triage",
  "action": "Fraud Triage",
  "line": "An order or transaction in context → a risk score, the signals driving it, and the checks worth running before you ship.",
  "method": "POST",
  "path": "/v1/fraud-flag",
  "fields": [],
  "key": "fraud-flag",
  "group": "commerce",
  "unit": "check",
  "blurb": "An order or transaction in context → a risk score, the signals driving it, and the checks worth running before you ship.",
  "credits": 6,
  "usd": 0.06,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "reply",
  "name": "Reply Drafting",
  "action": "Reply Drafting",
  "line": "A customer thread plus your context → a ready-to-send reply in the right tone, with an internal note for the agent.",
  "method": "POST",
  "path": "/v1/reply",
  "fields": [],
  "key": "reply",
  "group": "communication",
  "unit": "reply",
  "blurb": "A customer thread plus your context → a ready-to-send reply in the right tone, with an internal note for the agent.",
  "credits": 5,
  "usd": 0.05,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "triage",
  "name": "Ticket Triage",
  "action": "Ticket Triage",
  "line": "A support ticket → priority, category, the team it belongs to, sentiment, SLA risk, and a suggested first response.",
  "method": "POST",
  "path": "/v1/triage",
  "fields": [],
  "key": "triage",
  "group": "communication",
  "unit": "ticket",
  "blurb": "A support ticket → priority, category, the team it belongs to, sentiment, SLA risk, and a suggested first response.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 300,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "minutes",
  "name": "Meeting Minutes",
  "action": "Meeting Minutes",
  "line": "A meeting transcript → clean minutes: summary, decisions made, action items with owners, and open questions.",
  "method": "POST",
  "path": "/v1/minutes",
  "fields": [],
  "key": "minutes",
  "group": "communication",
  "unit": "transcript",
  "blurb": "A meeting transcript → clean minutes: summary, decisions made, action items with owners, and open questions.",
  "credits": 6,
  "usd": 0.06,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "outreach",
  "name": "Outreach Sequence",
  "action": "Outreach Sequence",
  "line": "An enriched lead plus what you sell → a personalized outreach sequence that references what actually makes them a fit.",
  "method": "POST",
  "path": "/v1/outreach",
  "fields": [],
  "key": "outreach",
  "group": "communication",
  "unit": "sequence",
  "blurb": "An enriched lead plus what you sell → a personalized outreach sequence that references what actually makes them a fit.",
  "credits": 6,
  "usd": 0.06,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "review-reply",
  "name": "Review Response",
  "action": "Review Response",
  "line": "A customer review → a brand-safe public response, the issues to log, and whether it needs human escalation.",
  "method": "POST",
  "path": "/v1/review-reply",
  "fields": [],
  "key": "review-reply",
  "group": "communication",
  "unit": "review",
  "blurb": "A customer review → a brand-safe public response, the issues to log, and whether it needs human escalation.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "moderate",
  "name": "Content Moderation",
  "action": "Content Moderation",
  "line": "Text or an image against YOUR policy → allow, review, or block, with the categories and excerpts that drove the call.",
  "method": "POST",
  "path": "/v1/moderate",
  "fields": [],
  "key": "moderate",
  "group": "content",
  "unit": "item",
  "blurb": "Text or an image against YOUR policy → allow, review, or block, with the categories and excerpts that drove the call.",
  "credits": 2,
  "usd": 0.02,
  "rate": {
   "limit": 300,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "rewrite",
  "name": "Brand-Voice Rewrite",
  "action": "Brand-Voice Rewrite",
  "line": "Any copy → your brand voice. Describe the voice or paste a sample; get the rewrite and what changed.",
  "method": "POST",
  "path": "/v1/rewrite",
  "fields": [],
  "key": "rewrite",
  "group": "content",
  "unit": "call",
  "blurb": "Any copy → your brand voice. Describe the voice or paste a sample; get the rewrite and what changed.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "product-copy",
  "name": "Product Copy",
  "action": "Product Copy",
  "line": "Specs and an audience → listing-ready titles, bullets, a description, and SEO keywords , per channel.",
  "method": "POST",
  "path": "/v1/product-copy",
  "fields": [],
  "key": "product-copy",
  "group": "content",
  "unit": "product",
  "blurb": "Specs and an audience → listing-ready titles, bullets, a description, and SEO keywords , per channel.",
  "credits": 5,
  "usd": 0.05,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "describe",
  "name": "Image Description",
  "action": "Image Description",
  "line": "An image → accessible alt text, a caption, tags, and any text found inside it. Accessibility and catalogs in one call.",
  "method": "POST",
  "path": "/v1/describe",
  "fields": [],
  "key": "describe",
  "group": "content",
  "unit": "image",
  "blurb": "An image → accessible alt text, a caption, tags, and any text found inside it. Accessibility and catalogs in one call.",
  "credits": 3,
  "usd": 0.03,
  "rate": {
   "limit": 120,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "research",
  "name": "Research Brief",
  "action": "Research Brief",
  "line": "A company or topic → a multi-source, citation-backed brief: what it is, what changed lately, and what matters. Real web work.",
  "method": "POST",
  "path": "/v1/research",
  "fields": [],
  "key": "research",
  "group": "web",
  "unit": "brief",
  "blurb": "A company or topic → a multi-source, citation-backed brief: what it is, what changed lately, and what matters. Real web work.",
  "credits": 50,
  "usd": 0.5,
  "rate": {
   "limit": 10,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "screen",
  "name": "Lead Screening",
  "action": "Lead Screening",
  "line": "A lead plus your ICP criteria → a web-grounded qualification verdict with the evidence for and against.",
  "method": "POST",
  "path": "/v1/screen",
  "fields": [],
  "key": "screen",
  "group": "web",
  "unit": "lead",
  "blurb": "A lead plus your ICP criteria → a web-grounded qualification verdict with the evidence for and against.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "transcribe",
  "name": "Transcription",
  "action": "Transcription",
  "line": "An audio recording → accurate text with speakers and paragraph timestamps. Meetings, calls, voice notes.",
  "method": "POST",
  "path": "/v1/transcribe",
  "fields": [],
  "key": "transcribe",
  "group": "media",
  "unit": "recording",
  "blurb": "An audio recording → accurate text with speakers and paragraph timestamps. Meetings, calls, voice notes.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": {
   "since": "2026-08-19",
   "reason": "Audio transcription needs a multimodal provider we can run under a no-training agreement. Every other endpoint already does; this one is paused rather than served on terms that would contradict our privacy commitment."
  },
  "takesFile": false
 },
 {
  "value": "memory",
  "name": "Agent Memory",
  "action": "Agent Memory",
  "line": "Store, search, and forget memories for your agents , semantic recall on your own namespace, no vector DB to run.",
  "method": "POST",
  "path": "/v1/memory",
  "fields": [],
  "key": "memory",
  "group": "media",
  "unit": "operation",
  "blurb": "Store, search, and forget memories for your agents , semantic recall on your own namespace, no vector DB to run.",
  "credits": 2,
  "usd": 0.02,
  "rate": {
   "limit": 300,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "image",
  "name": "Image Generation",
  "action": "Image Generation",
  "line": "A prompt → a production-ready image. Marketing visuals, product scenes, and consistent brand imagery.",
  "method": "POST",
  "path": "/v1/image",
  "fields": [],
  "key": "image",
  "group": "media",
  "unit": "image",
  "blurb": "A prompt → a production-ready image. Marketing visuals, product scenes, and consistent brand imagery.",
  "credits": 10,
  "usd": 0.1,
  "rate": {
   "limit": 30,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 },
 {
  "value": "speak",
  "name": "Text to Speech",
  "action": "Text to Speech",
  "line": "Text → natural speech audio, ready to embed. Voice notes, IVR lines, narration.",
  "method": "POST",
  "path": "/v1/speak",
  "fields": [],
  "key": "speak",
  "group": "media",
  "unit": "clip",
  "blurb": "Text → natural speech audio, ready to embed. Voice notes, IVR lines, narration.",
  "credits": 5,
  "usd": 0.05,
  "rate": {
   "limit": 60,
   "windowSec": 60
  },
  "paused": null,
  "takesFile": false
 }
] as const;
