#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs this site draws, from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the source, never from another product's tree. A copy of a copy has no source to
 * re-read, and the estate has no shared component library to take one from: those repos were
 * purged on 2026-09-14 and every app vendors its own set.
 *
 * The glyph list below is THIS site's. Every entry names the one place it is drawn, so a glyph
 * with no caller is a glyph to delete rather than one to keep in case.
 *
 * Compiled into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes the ink of
 * whatever sits beside it. No icon font, no runtime CDN. The n8n mark is NOT here: a vendor mark
 * is theirs, it stays in their own colour, and it comes from their own logo kit.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

const WANT = [
  'caret-up-down',        // the app switch beside the mark
  'caret-right',          // an operation row that opens
  'copy',                 // the masthead action and every copy button
  'terminal-window',      // the install line
  'plugs-connected',      // the Console destination, and the node inside a workflow
  'key',                  // the credential destination and the credential band
  'seal-check',           // the verification destination and a requirement that is met
  'list-magnifying-glass',// the method destination
  'file-text',            // the Documents group
  'brackets-curly',       // the Extract and structure group
  'shopping-cart',        // the Commerce and ops group
  'chat-teardrop-text',   // the Communication group
  'shield-check',         // the Content and moderation group
  'globe-hemisphere-west',// the Web and research group
  'robot',                // the Media and agents group
  'squares-four',         // every group at once
  'coins',                // a credit price
  'check',                // a requirement this package satisfies
  'pause',                // the one operation the catalogue has paused
  'warning-circle',       // a figure on the package that disagrees with the node source
  'clock',                // a read date
  'arrow-square-out',     // an outward link
  'paperclip',            // an operation that takes a file URL
  'text-aa',              // an operation that takes text
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
